name: Deploy to GitHub Pages (external repo)

on:
  push:
    branches: [main]
  workflow_dispatch: {}

concurrency:
  group: pages-deploy
  cancel-in-progress: true

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Setup Node.js 20 (npm)
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json

      - name: Install dependencies (frontend) with npm
        working-directory: frontend
        run: |
          if [ -f package-lock.json ]; then
            npm ci
          else
            npm install
          fi

      - name: Build (frontend)
        working-directory: frontend
        run: |
          npm run build

      - name: Deploy to external Pages repo
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.PAGES_TOKEN }}
          external_repository: PisoDev77/PisoDev77.github.io
          publish_branch: main
          publish_dir: frontend/build
          commit_message: 'Deploy: ${{ github.repository }}@${{ github.sha }} (npm)'
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
