name: Deploy to GitHub Pages (external repo)

on:
  push:
    branches: [main]
  workflow_dispatch: {}

concurrency:
  group: pages-deploy
  cancel-in-progress: true

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Setup Node.js 20 and Yarn 1 (Classic)
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'yarn'
          cache-dependency-path: frontend/yarn.lock
      - name: Activate Yarn Classic via Corepack
        run: |
          corepack enable
          corepack prepare yarn@1.22.22 --activate
          yarn --version

      - name: Install dependencies (frontend)
        working-directory: frontend
        run: |
          yarn install --frozen-lockfile

      - name: Build (frontend)
        working-directory: frontend
        run: |
          yarn build

      - name: Deploy to external Pages repo
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.PAGES_TOKEN }}
          external_repository: PisoDev77/PisoDev77.github.io
          publish_branch: main
          publish_dir: frontend/build
          commit_message: 'Deploy: ${{ github.repository }}@${{ github.sha }}'
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
